version: '3'

services:
  frontend:
    image: frontend_image:latest
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  backend:
    image: backend_image:latest
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - 5000:5000