version: "3"

services:
  frontend:
    image: frontend_image:latest
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app/
      - /app/node_modules
    ports:
      - 5000:5000
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  backend:
    image: backend_image:latest
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
