version: "3"

services:
  frontend:
    image: frontend_image:latest
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app/
      - /app/node_modules
    ports:
      - 5000:5000
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: sh -c "npm install && npm run dev"

  backend:
    image: backend_image:latest
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: sh -c "npm install && nodemon app.js"

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: database
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "root"
